### ISSUE TITLE
Still taking contributions?

### ISSUE THREAD

**Issue by deleterepo** [OWASP/www-project-code-review-guide#12]
Hi I really liked v2.0 of this project and was wondering if v3.0 is still in the works? I'd be interested in making some contributions.

**Comment by kingthorin** [comment]
Yup. Your best bet is to [join OWASP global slack](https://owasp.org/slack.invite) and hit the `#project-secure-code-review-guide` channel to discuss things. It is also VERY low traffic but hopefully people will chime in and help you get going.
