### ISSUE TITLE
Threat Modeling Methodology

### ISSUE THREAD

**Issue by nanzggits** [OWASP/www-project-code-review-guide#9]
Add section for Threat Modeling Methodology

**Comment by mgreiler** [comment]
- [ ] Ask developers to use STRIDE during code reviews (was it helpful? what was missing?)

**Comment by mgreiler** [comment]
The outcome of the brainstorm session on 28.1.2022

- how traditional thread modeling fits into frequent code reviews (daily or several times a week), is not completely clear.
- we could use it to help developers reason about a code change and create a security-focused metal model
- it could also inspire which part of the secure code review checklist you look at
